# Generated by Django 4.1 on 2022-08-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoticketapp', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='pasword',
            new_name='password',
        ),
    ]
