# Generated by Django 4.1 on 2022-08-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoticketapp', '0003_rename_pasword_login_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='created_at',
            new_name='senddate',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='licenseno',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='ticket',
            name='serverdetails',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketno',
            field=models.CharField(default='', max_length=100),
        ),
    ]
