# Generated by Django 4.1 on 2022-08-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoticketapp', '0004_rename_created_at_ticket_senddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musername', models.CharField(max_length=20)),
                ('mpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
