# Generated by Django 4.1 on 2022-08-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoticketapp', '0005_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='djangoticketapp.register'),
        ),
    ]
