# Generated by Django 4.1 on 2022-08-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musername', models.CharField(max_length=20)),
                ('mpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketno', models.CharField(default='', max_length=100)),
                ('serverdetails', models.CharField(default='', max_length=100)),
                ('senddate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('licenseno', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='djangoticketapp.register')),
            ],
        ),
    ]
