# Generated by Django 4.1 on 2022-08-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mfile',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
