# Generated by Django 4.0.6 on 2022-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoticketapp', '0002_ticket_mfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='mrole',
            field=models.CharField(default='', max_length=20),
        ),
    ]
