# Generated by Django 4.0.6 on 2022-08-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoticketapp', '0003_register_mrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='mrole',
            new_name='marole',
        ),
        migrations.AddField(
            model_name='register',
            name='murole',
            field=models.CharField(default='', max_length=20),
        ),
    ]
