# Generated by Django 4.0.6 on 2022-08-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoticketapp', '0005_login_malrole_login_mulrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user_id',
        ),
    ]
